fix the delete method path
internetbrands/ike-artifactory-ruby pull request #6
Opened 2021-12-10 14:06 UTC by kavehmz

It seems during refactoring path for delete and get which were separate where unified wrongly which this PR should fix it.

2021-12-13 12:34 UTC, vicente-ramos commented
@kavehmz Looks good to me.

2022-02-25 19:58 UTC, nickmarden requested changes
If we are going to write `bin/cleaner.rb` the way it is suggested, we should not throw away arguments that come before the `--actually-delete` and `--delete-empty-path` switches.

2022-02-25 19:58 UTC, nickmarden commented on bin/cleaner.rb
> +  arg = ARGV.shift
So I think this says "if there are any arguments before `--actually-delete` and `--delete-empy-path`, throw those arguments away and ignore them"

2022-02-25 19:59 UTC, nickmarden commented on bin/cleaner.rb
> +  arg = ARGV.shift
Oh wait, I misread this. Please ignore my comment.

2022-02-25 19:59 UTC, nickmarden approved these changes

2022-02-25 20:00 UTC, nickmarden commented on bin/cleaner.rb
> +  if arg == '--delete-empty-path'
Need to update the usage statement.

2022-03-02 13:25 UTC, nickmarden approved these changes

2022-03-02 13:43 UTC, merged